Repository Team7-MediaProject/7-Video, pull requests merged in 2023-09, with the labels that each got.

#8 Design/home page
  app/build.gradle
  app/src/main/res/drawable/fandom.png
  app/src/main/res/layout/category_channel_item.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/most_popular_item.xml
Labels: Design🎨

#9 [Design] HomePage - Category Videos
  .idea/.name
  .idea/deploymentTargetDropDown.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/vcs.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/teamtube/HomeData.kt
  app/src/main/java/com/example/teamtube/HomeFragmentAdapter.kt
  app/src/main/java/com/example/teamtube/MainActivity.kt
  app/src/main/res/drawable/icon_nav_home.xml
  app/src/main/res/drawable/icon_nav_myvideo.xml
  app/src/main/res/drawable/icon_nav_search.xml
  app/src/main/res/drawable/round_box.xml
  app/src/main/res/drawable/sample1.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/category_channel_item.xml
  app/src/main/res/layout/category_video_item.xml
  app/src/main/res/layout/fragment_home.xml
Labels: Design🎨

#10 [DESIGN] MyPage 디자인, 리사이클러뷰 아이템 추가
  .idea/misc.xml
  app/src/main/res/layout/fragment_my_video.xml
  app/src/main/res/layout/liked_channel_item.xml
  app/src/main/res/layout/liked_video_item.xml
Labels: Design🎨

#11 [Design] Detail Page commit
  .idea/.name
  .idea/gradle.xml
  .idea/vcs.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/teamtube/VideoDetailAcitvity.kt
  app/src/main/res/drawable/downarrow.png
  app/src/main/res/drawable/sample5.png
  app/src/main/res/layout/activity_detail.xml
Labels: Design🎨

#14 Design/home page dogyun
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/teamtube/SearchFragment.kt
  app/src/main/java/com/example/teamtube/VideoDetailAcitvity.kt
  app/src/main/res/drawable/downarrow.png
  app/src/main/res/drawable/ic_searchfragment_search.xml
  app/src/main/res/drawable/sample5.png
  app/src/main/res/drawable/searchfragment_btn_click_background.xml
  app/src/main/res/drawable/searchfragment_btn_click_color.xml
  app/src/main/res/drawable/searchfragment_btn_round_color.xml
  app/src/main/res/drawable/searchfragment_et_round_corner_rectangle.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/fragment_my_video.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/liked_channel_item.xml
  app/src/main/res/layout/liked_video_item.xml
  app/src/main/res/values/style.xml
  app/src/main/res/values/themes.xml
Labels: Fix🔧

#15 [Design] HomePage 구현완료
  .idea/deploymentTargetDropDown.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/teamtube/HomeData.kt
  app/src/main/java/com/example/teamtube/HomeFragmentAdapter.kt
  app/src/main/java/com/example/teamtube/MainActivity.kt
  app/src/main/res/drawable/fandom.png
  app/src/main/res/drawable/icon_nav_home.xml
  app/src/main/res/drawable/icon_nav_myvideo.xml
  app/src/main/res/drawable/icon_nav_search.xml
  app/src/main/res/drawable/round_box.xml
  app/src/main/res/drawable/sample1.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/category_channel_item.xml
  app/src/main/res/layout/category_video_item.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/most_popular_item.xml
  app/src/main/res/values/style.xml
  app/src/main/res/values/themes.xml
Labels: Design🎨

#20 [DESIGN] 리사이클러뷰 아이템 삭제 및 변경
  app/src/main/res/layout/fragment_my_video.xml
  app/src/main/res/layout/liked_channel_item.xml
  app/src/main/res/layout/liked_video_item.xml
Labels: Design🎨

#21 [FEAT] : api 인기동영상 연결 완료
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/teamtube/HomeData.kt
  app/src/main/java/com/example/teamtube/HomeFragment.kt
  app/src/main/java/com/example/teamtube/HomeFragmentAdapter.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/most_popular_item.xml
Labels: Feature⚙️

#24 feature/design search fragment
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/teamtube/HomeFragment.kt
  app/src/main/java/com/example/teamtube/SearchFragment.kt
  app/src/main/java/com/example/teamtube/SearchFragmentAdapter.kt
  app/src/main/java/com/example/teamtube/SearchFragmentData/INetworkService.kt
  app/src/main/java/com/example/teamtube/SearchFragmentData/RetrofitClient.kt
  app/src/main/java/com/example/teamtube/SearchFragmentData/SearchData.kt
  app/src/main/java/com/example/teamtube/SearchFragmentData/SearchItem.kt
  app/src/main/java/com/example/teamtube/data/YouTubeApiService.kt
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_search_item.xml
Labels: Feature⚙️
