Repository Team7-MediaProject/7-Video, pull requests merged in 2023-10, with the labels that each got.

#27 [FIX] : 디자인수정
  app/src/main/java/com/example/teamtube/HomeFragment.kt
  app/src/main/java/com/example/teamtube/HomeFragmentAdapter.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/most_popular_item.xml
Labels: Design🎨

#28 Feature/search fragments
  app/src/main/java/com/example/teamtube/SearchFragment.kt
  app/src/main/res/layout/fragment_search.xml
Labels: Feature⚙️

#29 [FEAT] 채널API 연결(ID값 수정 필요)
  app/src/main/java/com/example/teamtube/ChannelData/ChannelApi.kt
  app/src/main/java/com/example/teamtube/ChannelData/ChannelApiService.kt
  app/src/main/java/com/example/teamtube/ChannelData/ChannelFragmentAdapter.kt
  app/src/main/java/com/example/teamtube/ChannelData/ChannelModel.kt
  app/src/main/java/com/example/teamtube/HomeFragment.kt
  app/src/main/res/layout/category_channel_item.xml
  app/src/main/res/layout/fragment_home.xml
Labels: Feature⚙️

#31 Design/home page
  app/src/main/java/com/example/teamtube/ChannelData/ChannelApi.kt
  app/src/main/java/com/example/teamtube/ChannelData/ChannelApiService.kt
  app/src/main/java/com/example/teamtube/HomeFragment.kt
  app/src/main/java/com/example/teamtube/MainActivity.kt
  app/src/main/java/com/example/teamtube/MostPopularData/DataModel.kt
  app/src/main/java/com/example/teamtube/MostPopularData/YouTubeApi.kt
  app/src/main/java/com/example/teamtube/MostPopularData/YouTubeApiService.kt
  app/src/main/java/com/example/teamtube/ViewPager2Adapter.kt
  app/src/main/res/layout/category_channel_item.xml
  app/src/main/res/layout/fragment_home.xml
Labels: Design🎨, Feature⚙️

#33 [Fix] Detail Activity -> Fragment
  .idea/.name
  .idea/deploymentTargetDropDown.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/vcs.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/teamtube/ChannelData/ChannelApi.kt
  app/src/main/java/com/example/teamtube/ChannelData/ChannelApiService.kt
  app/src/main/java/com/example/teamtube/ChannelData/ChannelFragmentAdapter.kt
  app/src/main/java/com/example/teamtube/ChannelData/ChannelModel.kt
  app/src/main/java/com/example/teamtube/HomeFragment.kt
  app/src/main/java/com/example/teamtube/HomeFragmentAdapter.kt
  app/src/main/java/com/example/teamtube/MainActivity.kt
  app/src/main/java/com/example/teamtube/MostPopularData/DataModel.kt
  app/src/main/java/com/example/teamtube/MostPopularData/YouTubeApi.kt
  app/src/main/java/com/example/teamtube/MostPopularData/YouTubeApiService.kt
  app/src/main/java/com/example/teamtube/SearchFragment.kt
  app/src/main/java/com/example/teamtube/SearchFragmentAdapter.kt
  app/src/main/java/com/example/teamtube/SearchFragmentData/INetworkService.kt
  app/src/main/java/com/example/teamtube/SearchFragmentData/RetrofitClient.kt
  app/src/main/java/com/example/teamtube/SearchFragmentData/SearchData.kt
  app/src/main/java/com/example/teamtube/SearchFragmentData/SearchItem.kt
  app/src/main/java/com/example/teamtube/VideoDetailAcitvity.kt
  app/src/main/java/com/example/teamtube/ViewPager2Adapter.kt
  app/src/main/java/com/example/teamtube/model/HomeitemModel.kt
  app/src/main/res/drawable/downarrow.png
  app/src/main/res/drawable/fandom.png
  app/src/main/res/drawable/ic_searchfragment_search.xml
  app/src/main/res/drawable/icon_nav_home.xml
  app/src/main/res/drawable/icon_nav_myvideo.xml
  app/src/main/res/drawable/icon_nav_search.xml
  app/src/main/res/drawable/round_box.xml
  app/src/main/res/drawable/sample1.png
  app/src/main/res/drawable/sample5.png
  app/src/main/res/drawable/searchfragment_btn_click_background.xml
  app/src/main/res/drawable/searchfragment_btn_click_color.xml
  app/src/main/res/drawable/searchfragment_btn_round_color.xml
  app/src/main/res/drawable/searchfragment_et_round_corner_rectangle.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/category_channel_item.xml
  app/src/main/res/layout/category_video_item.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_video.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_search_item.xml
  app/src/main/res/layout/most_popular_item.xml
  app/src/main/res/values/style.xml
  app/src/main/res/values/themes.xml
Labels: Fix🔧

#36 Feature/data api/kkomin
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/com/example/teamtube/Adapter/CategoryVideoAdapter.kt
  app/src/main/java/com/example/teamtube/Adapter/HomeFragmentAdapter.kt
  app/src/main/java/com/example/teamtube/Adapter/SearchFragmentAdapter.kt
  app/src/main/java/com/example/teamtube/Adapter/ViewPager2Adapter.kt
  app/src/main/java/com/example/teamtube/CategoryVideoData/CategoryList.kt
  app/src/main/java/com/example/teamtube/CategoryVideoData/Model/CategoryVideo.kt
  app/src/main/java/com/example/teamtube/CategoryVideoData/Model/Video.kt
  app/src/main/java/com/example/teamtube/CategoryVideoData/VideoInterface.kt
  app/src/main/java/com/example/teamtube/CategoryVideoData/VideoNetworkClient.kt
  app/src/main/java/com/example/teamtube/Constrant/Constrants.kt
  app/src/main/java/com/example/teamtube/Fragment/HomeFragment.kt
  app/src/main/java/com/example/teamtube/Fragment/MyVideoFragment.kt
  app/src/main/java/com/example/teamtube/Fragment/SearchFragment.kt
  app/src/main/java/com/example/teamtube/HomeFragment.kt
  app/src/main/java/com/example/teamtube/MainActivity.kt
  app/src/main/res/drawable/icon_nav_home.xml
  app/src/main/res/drawable/icon_nav_myvideo.xml
  app/src/main/res/drawable/icon_nav_search.xml
  app/src/main/res/layout/category_video_item.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_video.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/most_popular_item.xml
  app/src/main/res/values/colors.xml
  gradle.properties
Labels: Feature⚙️

#39 Feature/fragment/kkomin
  app/src/main/java/com/example/teamtube/Adapter/CategoryVideoAdapter.kt
  app/src/main/java/com/example/teamtube/Adapter/ChannelFragmentAdapter.kt
  app/src/main/java/com/example/teamtube/Adapter/HomeFragmentAdapter.kt
  app/src/main/java/com/example/teamtube/Adapter/SearchFragmentAdapter.kt
  app/src/main/java/com/example/teamtube/CategoryVideoData/CategoryList.kt
  app/src/main/java/com/example/teamtube/CategoryVideoData/VideoInterface.kt
  app/src/main/java/com/example/teamtube/ChannelData/ChannelApi.kt
  app/src/main/java/com/example/teamtube/ChannelData/ChannelApiService.kt
  app/src/main/java/com/example/teamtube/Fragment/HomeFragment.kt
  app/src/main/java/com/example/teamtube/Fragment/SearchFragment.kt
  app/src/main/java/com/example/teamtube/Fragment/VideoDetailFragmant.kt
  app/src/main/java/com/example/teamtube/HomeFragment.kt
  app/src/main/java/com/example/teamtube/Model/CategoryDataList.kt
  app/src/main/java/com/example/teamtube/Model/CategoryList.kt
  app/src/main/java/com/example/teamtube/Model/ChannelModel.kt
  app/src/main/java/com/example/teamtube/Model/HomeitemModel.kt
  app/src/main/java/com/example/teamtube/Model/SearchData.kt
  app/src/main/java/com/example/teamtube/MostPopularData/YouTubeApi.kt
  app/src/main/java/com/example/teamtube/MostPopularData/YouTubeApiService.kt
  app/src/main/java/com/example/teamtube/Retrofit/ApiData/CategoryVideoData/CategoryVideo.kt
  app/src/main/java/com/example/teamtube/Retrofit/ApiData/CategoryVideoData/Video.kt
  app/src/main/java/com/example/teamtube/Retrofit/ApiData/MostPopularData/MostPopularDataModel.kt
  app/src/main/java/com/example/teamtube/Retrofit/ApiData/SearchData/SearchItem.kt
  app/src/main/java/com/example/teamtube/Retrofit/retrofit/VideoInterface.kt
  app/src/main/java/com/example/teamtube/Retrofit/retrofit/VideoNetworkClient.kt
  app/src/main/java/com/example/teamtube/SearchFragmentData/INetworkService.kt
  app/src/main/java/com/example/teamtube/SearchFragmentData/RetrofitClient.kt
  app/src/main/res/drawable/sample1.png
  app/src/main/res/layout/category_video_item.xml
  app/src/main/res/layout/fragment_video_detail.xml
Labels: Fix🔧

#43 [Feature] Detail_Activity 데이터 호출
  app/src/main/java/com/example/teamtube/Adapter/CategoryVideoAdapter.kt
  app/src/main/java/com/example/teamtube/Adapter/HomeFragmentAdapter.kt
  app/src/main/java/com/example/teamtube/Adapter/SearchFragmentAdapter.kt
  app/src/main/java/com/example/teamtube/Fragment/HomeFragment.kt
  app/src/main/java/com/example/teamtube/Fragment/SearchFragment.kt
  app/src/main/java/com/example/teamtube/Model/CategoryList.kt
  app/src/main/java/com/example/teamtube/Model/HomeitemModel.kt
  app/src/main/java/com/example/teamtube/Model/SearchData.kt
  app/src/main/java/com/example/teamtube/VideoDetailActivity.kt
Labels: Feature⚙️

#44 Design/fragment/kkomin
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/teamtube/Activity/MainActivity.kt
  app/src/main/java/com/example/teamtube/Activity/SplashActivity.kt
  app/src/main/res/drawable/background.png
  app/src/main/res/drawable/blue_ghost.png
  app/src/main/res/drawable/cherry.png
  app/src/main/res/drawable/dots.png
  app/src/main/res/drawable/downarrow.png
  app/src/main/res/drawable/fandom.png
  app/src/main/res/drawable/icon_downarrow.xml
  app/src/main/res/drawable/image_ready.png
  app/src/main/res/drawable/pacman.png
  app/src/main/res/drawable/pacman_logo.png
  app/src/main/res/drawable/pink_ghost.png
  app/src/main/res/drawable/red_ghost.png
  app/src/main/res/drawable/round_box.xml
  app/src/main/res/drawable/searchfragment_btn_round_color.xml
  app/src/main/res/drawable/searchfragment_et_round_corner_rectangle.xml
  app/src/main/res/drawable/splash.png
  app/src/main/res/drawable/yellow_ghost.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/activity_video_detail.xml
  app/src/main/res/layout/category_channel_item.xml
  app/src/main/res/layout/category_video_item.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_video.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_search_item.xml
  app/src/main/res/layout/most_popular_item.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: Design🎨

#46 Feature/bundle search fragment
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/com/example/teamtube/Activity/MainActivity.kt
  app/src/main/java/com/example/teamtube/Adapter/SearchFragmentAdapter.kt
  app/src/main/java/com/example/teamtube/ChannelData/Fragment/SearchFragment.kt
  app/src/main/java/com/example/teamtube/Model/HomeitemModel.kt
  app/src/main/java/com/example/teamtube/VideoDetailActivity.kt
  app/src/main/res/drawable/ic_searchfragment_search.xml
  app/src/main/res/drawable/searchfragment_btn_click_background.xml
  app/src/main/res/layout/activity_video_detail.xml
Labels: Design🎨, Feature⚙️

#50 Feature/my video like channel/kkomin
  app/src/main/java/com/example/teamtube/Activity/MainActivity.kt
  app/src/main/java/com/example/teamtube/Adapter/CategoryVideoAdapter.kt
  app/src/main/java/com/example/teamtube/Adapter/MyVideoFragmentAdapter.kt
  app/src/main/java/com/example/teamtube/Fragment/HomeFragment.kt
  app/src/main/java/com/example/teamtube/Fragment/MyVideoFragment.kt
  app/src/main/java/com/example/teamtube/Fragment/SearchFragment.kt
Labels: Fix🔧

#53 Design/Feature 유튜브 플레이어 화면 크기 조절.
  app/src/main/java/com/example/teamtube/VideoDetailActivity.kt
  app/src/main/res/layout/activity_video_detail.xml
Labels: Design🎨, Feature⚙️

#54 [Feature] Detail Activity 데이터 받아오기
  app/src/main/java/com/example/teamtube/VideoDetailActivity.kt
  app/src/main/res/layout/activity_video_detail.xml
Labels: Feature⚙️

#55 [Fix] Detail Activity 동영상 재생 관련 부분 수정
  app/src/main/java/com/example/teamtube/VideoDetailActivity.kt
  app/src/main/res/layout/activity_video_detail.xml
Labels: Fix🔧

#57 [FEAT] MyVideoPage 비디오 좋아요 기능
  app/src/main/java/com/example/teamtube/Adapter/HomeFragmentAdapter.kt
  app/src/main/java/com/example/teamtube/Adapter/MyVideoAdapter.kt
  app/src/main/java/com/example/teamtube/Adapter/MyVideoFragmentAdapter.kt
  app/src/main/java/com/example/teamtube/Fragment/MyVideoFragment.kt
  app/src/main/java/com/example/teamtube/VideoDetailActivity.kt
  app/src/main/res/layout/activity_video_detail.xml
  app/src/main/res/layout/fragment_my_video.xml
Labels: Design🎨, Feature⚙️
